use_frameworks!

platform :ios, '9.0'

target 'TPFoundation-Swift_Example' do
  pod 'TPFoundation-Swift', :path => '../'

  target 'TPFoundation-Swift_Tests' do
    inherit! :search_paths

    
  end
end
